### ISSUE TITLE
fibocom-qmi-wwan: fail to build with kernel 6.18

### ISSUE THREAD

**Issue by xlighting2017** [immortalwrt/packages#1903]
### Package Name

fibocom-qmi-wwan

### ImmortalWrt Version

SNAPSHOT

### ImmortalWrt Target/Subtarget

mediatek/filogic

### Steps to Reproduce

the filogic is going to use kernel 6.18, but  `fibocom-qmi-wwan` failed to build with it, the error log says:
```
make[4]: Entering directory '/mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.18.21'
make[5]: Entering directory '/mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/fibocom-qmi-wwan-1.0.5'
  CC [M]  qmi_wwan_f.o
qmi_wwan_f.c: In function 'qmap_register_device':
qmi_wwan_f.c:1211:5: error: implicit declaration of function 'hrtimer_init'; did you mean 'hrtimers_init'? [-Wimplicit-function-declaration]
 1211 |     hrtimer_init(&priv->agg_hrtimer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
      |     ^~~~~~~~~~~~
      |     hrtimers_init
make[7]: *** [/mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.18.21/scripts/Makefile.build:287: qmi_wwan_f.o] Error 1

```

### Actual Behaviour

the root cause is that 
`hrtimer_init()` was deprecated when `hrtimer_setup()` was added in Kernel 6.13. 
As of Kernel 6.15 `hrtimer_init()` has been removed.

therefore it builds OK with 6.12, but failed with 6.18.

to solve it, we can either:
- add another "fix build for 6.18" patch, to use `hrtimer_setup()` if it's >= 6.15 and keep `hrtimer_init()` if it's <= 6.15
OR
- add a `hrtimer_init() wrapper using hrtimer_setup()` like it's done in ref[2]

ref: 
[1] https://github.com/asterisk/dahdi-linux/issues/93
[2] https://github.com/openwrt/telephony/pull/929

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the core repository](https://github.com/immortalwrt/immortalwrt/issues) or [LuCI repository](https://github.com/immortalwrt/luci/issues) will be closed.
- [x] I am reporting an issue for ImmortalWrt, not an unsupported fork.
